// DO NOT EDIT. This file is auto-generated by Firebase Studio.
// This is the configuration for your Firebase project.
// You can find it in the Firebase console.

// 1. Go to your project in the Firebase console: https://console.firebase.google.com/
// 2. In the project overview, click the "</>" icon to add a web app.
// 3. Register your app and copy the firebaseConfig object.
// 4. Paste it here.

export const firebaseConfig = {
  apiKey: "AIzaSyCVBNcigMe4JMgQ-MSoOi9jgQuDKGX6rt0",
  authDomain: "hostara-245a2.firebaseapp.com",
  projectId: "hostara-245a2",
  storageBucket: "hostara-245a2.appspot.com",
  messagingSenderId: "128439977035",
  appId: "1:128439977035:web:9c19faf6fa9e3f8b1c39ce",
  measurementId: "G-L4795XX9MF"
};
