// DO NOT EDIT. This file is auto-generated by Firebase Studio.
// This is the configuration for your Firebase project.
// You can find it in the Firebase console.

// 1. Go to your project in the Firebase console: https://console.firebase.google.com/
// 2. In the project overview, click the "</>" icon to add a web app.
// 3. Register your app and copy the firebaseConfig object.
// 4. Paste it here.

export const firebaseConfig = {
  apiKey: "PASTE_YOUR_API_KEY_HERE",
  authDomain: "PASTE_YOUR_AUTH_DOMAIN_HERE",
  projectId: "PASTE_YOUR_PROJECT_ID_HERE",
  storageBucket: "PASTE_YOUR_STORAGE_BUCKET_HERE",
  messagingSenderId: "PASTE_YOUR_MESSAGING_SENDER_ID_HERE",
  appId: "PASTE_YOUR_APP_ID_HERE"
};
